// React/demoapp/src/components/Updates/Update.js
import React, { Component } from 'react';

class Update extends Component {
    state = {  }
    render() { 
        return ( 
<li>
        <h6>{this.props.update.title}</h6>
    <p className="mt-2">{this.props.update.message}</p>
    <p className="text-muted mb-4">
        <i className="mdi mdi-clock-outline"></i>{this.props.update.time}
    </p>
</li>
         );
    }
}
 
export default Update;

// Vue/demoapp/src/components/Updates/Update.vue
<template>
<ul class="bullet-line-list mt-4">
    <li>
        <h6>{{update.title}}</h6>
        <p class="mt-2">{{update.message}}</p>
        <p class="text-muted mb-4">
            <i class="mdi mdi-clock-outline"></i> {{update.time}}
        </p>
    </li>
</ul>
</template>

<script>
export default {
    name : "Update",
    props: {
        update: Object
    }
}
</script>
