// Vue/demoapp/src/components/Navigation/Notification.vue
<template>
<a class="dropdown-item preview-item">
   <div class="preview-thumbnail">
      <div class="preview-icon bg" v-bind:class="iconColor(icon)">
        <i class="mdi mdi-information mx-0"></i>
      </div>
    </div>
  <div class="preview-item-content">
    <h6 class="preview-subject font-weight-normal">{{notification.title}}</h6>
      <p class="font-weight-light small-text mb-0 text-muted">
        {{notification.subtitle}}
      </p>
   </div>
</a>
</template>

<script>
export default {
    name : "Notification",
    props: {
        notification: Object
    },
     methods: {
      iconColor: (icon) => {
        switch(icon) {
          case "appError":
          return "bg-success"
          case "Settnings":
          return "bg-warning"
          case "appError2":
          return "bg-info"
          default:
          return "bg-warning"

        }
      }
    }
}
</script>

// React/demoapp/src/components/Navigation/Notification.js
import React, { Component } from 'react';

class Notification  extends Component {
    state = { } 
    render() { 
        return ( 
            <a className="dropdown-item preview-item">
            <div className="preview-thumbnail">
              <div className="preview-icon bg-success">
                <i className="mdi mdi-information mx-0"></i>
              </div>
            </div>
            <div className="preview-item-content">
              <h6 className="preview-subject font-weight-normal">{this.props.notification.title}</h6>
              <p className="font-weight-light small-text mb-0 text-muted">
              {this.props.notification.subtitle}
              </p>
            </div>
          </a>
       );
    }
}
 
export default Notification;
