// Vue/demoapp/src/components/Updates/Updates.vue
<template>
<div class="col-xl-4 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-title">Updates</p>

            <Update :key="update.time" v-for="update of updates" :update="update" />

        </div>
    </div>
</div>
</template>

<script>
import Update from "./Update"

export default {
  name: "Updates",
  components: {
    Update
  },
  data() {
    return {
      updates : []
    }
  },
  created() {
    fetch("https://inlupp-fa.azurewebsites.net/api/updates")
    .then(res => res.json())
    .then(data => {
      this.updates = data;
  
    })
  }
  
}
</script>

// React/demoapp/src/components/Updates/Updates.js
import React, { Component } from 'react';
import Update from './Update'

class Updates extends Component {
	constructor(props) {
		super(props);
		
		this.state = {
		  updates: []
		}  
	  }
	
	componentDidMount() {
		fetch("https://inlupp-fa.azurewebsites.net/api/updates")
		.then(res => res.json())
		.then(data => {
		this.setState({updates: data})
		})
	  }
    render() { 
        return ( 
            
            <div className="col-xl-4 grid-margin stretch-card">
              <div className="card">
				<div className="card-body">
			    	<p className="card-title">Updates</p>
					    <ul className="bullet-line-list mt-4">
							
						{ this.state.updates.map((update) => (<Update key={update.time} update={update} />)) }

						</ul>
				    </div>
				</div>
              </div>
         );
    }
}
 
export default Updates;
