// React/demoapp/src/components/Total/TotalUsers.js
import React, { Component } from 'react';

class TotalUsers extends Component {
    state = { 
      totalUsers: {}
     }

 async componentDidMount() {
      const tu = await fetch('https://inlupp-fa.azurewebsites.net/api/total-users');
      const tudata = await tu.json();
      this.setState({totalUsers: tudata})
     }
    render() { 
        return ( 
            <div className="col-md-6 grid-margin stretch-card">
                  <div className="card">
                    <div className="card-body">
                      <p className="card-title">Users</p>
                      <div className="d-flex flex-wrap align-items-baseline">
                        <h2 className="mr-3">{this.state.totalUsers.users}</h2>
                        <i className="mdi mdi-arrow-up mr-1 text-danger"></i><span><p className="mb-0 text-danger font-weight-medium">+2.12%</p></span>
                      </div>
                      <p className="mb-0 text-muted">Total users world wide</p>
                    </div>
                    <canvas id="users-chart"></canvas>
                  </div>
                </div>

         );
    }
}
 
export default TotalUsers;

// Vue/demoapp/src/components/Total/TotalUsers.vue
<template>
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-title">Users</p>
            <div class="d-flex flex-wrap align-items-baseline">
                <h2 class="mr-3">{{totalUsers.users}}</h2>
                <i class="mdi mdi-arrow-up mr-1 text-danger"></i><span><p class="mb-0 text-danger font-weight-medium">{{totalUsers.growth}}%</p></span>
            </div>
            <p class="mb-0 text-muted">Total users world wide</p>
        </div>
        <canvas id="users-chart"></canvas>
    </div>
</div>
</template>

<script>
export default {
    name: "TotalUsers",
    data() {
        return {
            totalUsers: {}
        }
    },
    created() {
      fetch('https://inlupp-fa.azurewebsites.net/api/total-users')
      .then(res => res.json())
      .then(data => {
       this.totalUsers = data;
      })
    }
}
</script>
