// Angular/demoapp/src/app/components/Total/totalprojects/totalprojects/totalprojects.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-totalprojects',
  templateUrl: './totalprojects.component.html',
  styleUrls: ['./totalprojects.component.css']
})
export class TotalprojectsComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-title">Projects</p>
            <div class="d-flex flex-wrap align-items-baseline">
                <h2 class="mr-3">50.36%</h2>
                <i class="mdi mdi-arrow-up mr-1 text-success"></i><span><p class="mb-0 text-success font-weight-medium">+9.12%</p></span>
            </div>
            <p class="mb-0 text-muted">Total users world wide</p>
        </div>
        <canvas id="projects-chart"></canvas>
    </div>
</div>

// React/demoapp/src/components/Total/TotalProjects.js
import React, { Component } from 'react';

class TotalProjects  extends Component {
    state = { 
      totalProjects: {}
     }
     async componentDidMount() {
      const tp = await fetch('https://inlupp-fa.azurewebsites.net/api/total-projects');
      const tpdata = await tp.json();
      this.setState({totalProjects: tpdata})
     }
    render() { 
        return ( 
            <div className="col-md-6 grid-margin stretch-card">
                  <div className="card">
                    <div className="card-body">
                      <p className="card-title">Projects</p>
                      <div className="d-flex flex-wrap align-items-baseline">
                        <h2 className="mr-3">{this.state.totalProjects.projects}%</h2>
                        <i className="mdi mdi-arrow-up mr-1 text-success"></i><span><p className="mb-0 text-success font-weight-medium">+9.12%</p></span>                          
                      </div>
                      <p className="mb-0 text-muted">Total users world wide</p>
                    </div>
                    <canvas id="projects-chart"></canvas>
                  </div>
                </div>
         );
    }
}
 
export default TotalProjects;
