// React/demoapp/src/components/Navigation/Message.js
import React, { Component } from 'react';

class Message  extends Component {
    state = { } 
    render() { 
        return ( 
          <a className="dropdown-item preview-item">
          <div className="preview-thumbnail">
              <img src="https://via.placeholder.com/36x36" alt="image" className="profile-pic" />
          </div>
          <div className="preview-item-content flex-grow">
            <h6 className="preview-subject ellipsis font-weight-normal">{this.props.message.from}
            </h6>
            <p className="font-weight-light small-text text-muted mb-0">
                {this.props.message.title}
            </p>
          </div>
        </a>
       );
    }
}
 
export default Message;

// Vue/demoapp/src/components/Navigation/Message.vue
<template>
<a class="dropdown-item preview-item">
    <div class="preview-thumbnail">
        <img src="https://via.placeholder.com/36x36" alt="image" class="profile-pic">
    </div>
    <div class="preview-item-content flex-grow">
        <h6 class="preview-subject ellipsis font-weight-normal"> 
               {{message.from}}
           </h6>
        <p class="font-weight-light small-text text-muted mb-0">
            {{message.title}}
        </p>
    </div>
</a>          
</template>

<script>
export default {
    name : "Message",
    props: {
        message: Object
    }
}
</script>
