// React/demoapp/src/components/Total/TotalUsers.js
import React, { Component } from 'react';

class TotalUsers extends Component {
    state = { 
      totalUsers: {}
     }

 async componentDidMount() {
      const tu = await fetch('https://inlupp-fa.azurewebsites.net/api/total-users');
      const tudata = await tu.json();
      this.setState({totalUsers: tudata})
     }
    render() { 
        return ( 
            <div className="col-md-6 grid-margin stretch-card">
                  <div className="card">
                    <div className="card-body">
                      <p className="card-title">Users</p>
                      <div className="d-flex flex-wrap align-items-baseline">
                        <h2 className="mr-3">{this.state.totalUsers.users}</h2>
                        <i className="mdi mdi-arrow-up mr-1 text-danger"></i><span><p className="mb-0 text-danger font-weight-medium">+2.12%</p></span>
                      </div>
                      <p className="mb-0 text-muted">Total users world wide</p>
                    </div>
                    <canvas id="users-chart"></canvas>
                  </div>
                </div>

         );
    }
}
 
export default TotalUsers;

// Angular/demoapp/src/app/components/Total/totalusers/totalusers/totalusers.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-totalusers',
  templateUrl: './totalusers.component.html',
  styleUrls: ['./totalusers.component.css']
})
export class TotalusersComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <p class="card-title">Users</p>
        <div class="d-flex flex-wrap align-items-baseline">
            <h2 class="mr-3">33,956</h2>
            <i class="mdi mdi-arrow-up mr-1 text-danger"></i><span><p class="mb-0 text-danger font-weight-medium">+2.12%</p></span>
        </div>
        <p class="mb-0 text-muted">Total users world wide</p>
      </div>
      <canvas id="users-chart"></canvas>
    </div>
  </div>
